language: python
python:
  - "3.6"
install:
  - pip install coveralls
before_script:
  - pip install -r requirements.txt
  - git checkout ft-add-pagination
  - git checkout ft-add-paginattion
script:
  - nosetests --with-coverage --cover-package=application
after_success:
  - coveralls
